name: 'Send PR Review Reminders'
description: 'A custom action to send PR review reminders.'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  reminder_message:
    description: 'Reminder message'
    required: true
  review_turnaround_hours:
    description: 'Review turnaround time in hours'
    required: true
runs:
  using: 'node20'
  main: 'index.js'