name: 'Send PR Review Reminders'
description: 'An action to send PR review reminders'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  reminder_message:
    description: 'Reminder message to send'
    required: true
  review_turnaround_hours:
    description: 'Review turnaround time in hours'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
