name: PR Review Reminder

on:
  schedule:
  - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send PR Review Reminders
      uses: ./.github/actions/send-pr-reminders
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reminder_message: 'Please review this PR.'
        review_turnaround_hours: 1
