name: PR Review Reminder

on:
  schedule:
  - cron: "0 12,22 * * * *" # Runs every 5 minutes for testing
  workflow_dispatch:


jobs:
  send-reminders:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send PR Review Reminders
      uses: ./.github/actions/send-pr-reminders
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # reminder_message: 'Please review this PR.'
        review_turnaround_minutes: 1
